### ISSUE TITLE
Search in the agenda files

### ISSUE THREAD

**Issue by Ypot** [beacoder/org-searcher#1]
Hi 

In the readme I can see a reference to org agenda files: 
```
    (require 'org-ivy-search)
    (setq org-agenda-files '("~/workspace/org/"))
    (global-set-key (kbd "C-c o") #'org-ivy-search-view)
```
But it seems that the search is only done in the active buffer, is it possible to search in all the agenda files?

**Comment by beacoder** [comment]
Hi,
you don't need to open any org files, you only need to specify the path to
all the org files.

(setq org-agenda-files '("~/workspace/org/"))

the org-ivy-search-view will automatically open all the org files and
search for the texts you typed in.

so no worries, you could try for yourself.

Thanks.

**Comment by Ypot** [comment]
I don't know what happened, now it searches in the agenda files, although it doesn't show the results in a different buffer, just in the minibuffer.

**Comment by beacoder** [comment]
I haven't come across the issue you mentioned here before, but I would
suggest you could have a look at my emacs setup repo here:
https://github.com/beacoder/dot-emacs, see if you could figure out how to
fix the issue you mentioned here.

thanks.

Ypot ***@***.***> 于2024年5月12日周日 03:22写道：
